#!/usr/bin/env bash

java -jar compiler.jar                         \
	--language_in ECMASCRIPT_NEXT              \
	--language_out ECMASCRIPT5                 \
	--js js/closure-library/closure/goog/debug/**.js \
	--js js/closure-library/closure/goog/useragent/**.js \
	--js js/closure-library/closure/goog/dom/**.js \
	--js js/closure-library/closure/goog/array/**.js \
	--js js/closure-library/closure/goog/events/**.js \
    --js js/closure-library/closure/goog/reflect/**.js \
    --js js/closure-library/closure/goog/disposable/**.js \
    --js js/closure-library/closure/goog/string/**.js \
    --js js/closure-library/closure/goog/async/**.js \
    --js js/closure-library/closure/goog/labs/**.js \
    --js js/closure-library/closure/goog/uri/**.js \
    --js js/closure-library/closure/goog/structs/**.js \
    --js js/closure-library/closure/goog/functions/**.js \
    --js js/closure-library/closure/goog/iter/**.js \
    --js js/closure-library/closure/goog/math/**.js \
    --js js/closure-library/closure/goog/log/**.js \
    --js js/closure-library/closure/goog/json/**.js \
    --js js/closure-library/closure/goog/object/**.js \
    --js js/closure-library/closure/goog/net/**.js \
    --js js/closure-library/closure/goog/asserts/**.js \
    --js js/closure-library/closure/goog/promise/**.js \
    --js js/closure-library/closure/goog/event/**.js \
    --js js/closure-library/closure/goog/timer/**.js \
    --js js/closure-library/closure/goog/**.js \
    --js js/Matrix/Cells.js                    \
	--js js/Matrix/Model.js                    \
    --js js/Matrix/mxXHR.js                    \
    --js js/Matrix/mxWeb.js                    \
    --js js/SithTrak.js                        \
    --externs js/extRouter.js                  \
    --dependency_mode strict \
    --entry_point js/SithTrak.js \
	--compilation_level ADVANCED_OPTIMIZATIONS   \
	--js_output_file dist/SithTrak.adv.js

