export const APPLICATION_MOUNTING = 'APPLICATION_MOUNTING';
export const SCROLLED_UP = 'SCROLLED_UP';
export const SCROLLED_DOWN = 'SCROLLED_DOWN';

// API related
export const SITH_LOADING_STARTED = 'SITH_LOADING_STARTED';
export const SITH_LOADED = 'SITH_LOADED';
export const PLANET_CHANGED = 'PLANET_CHANGED';
